server:
  port: ${DISPATCHER_PORT:8084}

bot:
  name: ${TG_BOT_NAME}
  token: ${TG_BOT_TOKEN}

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:userok}
    password: ${RABBIT_PASSWORD:p@ssw0rd}
    queues:
      text-message-update: ${RABBIT_TEXT_MESSAGE_UPDATE_QUEUE}
      doc-message-update: ${RABBIT_DOC_MESSAGE_UPDATE_QUEUE}
      photo-message-update: ${RABBIT_PHOTO_MESSAGE_UPDATE_QUEUE}
      answer-message: ${RABBIT_ANSWER_MESSAGE_QUEUE}
