server:
  port: ${REST_SERVICE_PORT:8086}
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/pogreb}
    username: ${POSTGRES_USERNAME:userok}
    password: ${POSTGRES_PASSWORD:p@ssw0rd}
  jpa:
    generate-ddl: true

salt: ${SALT:test}
